name: web-app-workflow
on: 
  push:
    branches:
      - main
      - dev
      # - feature/*
env:
  MONGO_DB_NAME: gha-demo
  MONGO_URL: ${{ secrets.MONGO_URL }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load & cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: "false"
      - name: Output info
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Lint
        run: npm run lint

  build:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
        # set-output not working any more
        # run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file:{}' ';'
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # for open id permission
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: output files
        run: ls
      - name: output filename
        run: echo "${{ needs.build.outputs.script-file}}"
      - name: Get AWS permissions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::486122642263:role/github-demo
          aws-region: us-east-1
      - name: Deploy
        uses: ./.github/actions/deploy-s3-js
        with:
          bucket: my-test-bucket
          dist-folder: ./dist
          bucket-region: us-east-1
      - name: Output URL
        run: echo "Deployed to ${{ steps.deploy.outputs.website-url }}"

  information:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run js custom action
        uses: ./github/actions/deploy-s3-js
